### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by DanConwayDev** [lez/git-remote-blossom#1]
following the install instructions in the readme I get the following error on step `pip install .`
```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/user/dev/clones/git-remote-nostr/setup.py", line 10, in <module>
          with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen codecs>", line 906, in open
      FileNotFoundError: [Errno 2] No such file or directory: '/home/user/dev/clones/git-remote-nostr/README.rst'
      [end of output]
```

**Comment by lez** [comment]
fixed on master
